MENU = {
    "espresso": {
        "ingredients": {
            "water": 50,
            "coffee": 18,
        },
        "cost": 1.5,
    },
    "latte": {
        "ingredients": {
            "water": 200,
            "milk": 150,
            "coffee": 24,
        },
        "cost": 2.5,
    },
    "cappuccino": {
        "ingredients": {
            "water": 250,
            "milk": 100,
            "coffee": 24,
        },
        "cost": 3.0,
    }
}

resources = {
    "water": 300,
    "milk": 200,
    "coffee": 100,
}

resources = resources.copy()
menu = MENU.copy()
money = 0


def report():
    """
    :return: Report
    """
    print(f"Water : {resources['water']} ml")
    print(f"Milk : {resources['milk']} ml")
    print(f"Coffee : {resources['coffee']} g")
    print(f"Money : ${money}")


def payment():
    """
     :return: The cumulative amount after coin insertion.
    """
    print("Please enter coins")
    quarters = float(input("How many quarters?:"))
    dimes = float(input("How many dimes?:"))
    nickles = float(input("How many nickles?:"))
    pennies = float(input("How many pennies?:"))
    return (quarters * 0.25) + (dimes * 0.10) + (nickles * 0.05) + (pennies * 0.01)


def transaction(drink):
    """
    :return: The change if the amount generated by coins are greater than the cost.
    """
    coins = payment()
    if coins >= menu[drink]["cost"]:
        print(f"Here is $ {round(coins - menu[drink]['cost'], 3)} in change.")
        global money
        money += menu[drink]['cost']
        return True
    elif coins < menu[drink]["cost"]:
        return False


def check_sufficient_resources(drink):
    for item in menu[drink]["ingredients"]:
        if menu[drink]["ingredients"][item] < resources[item]:
            make_coffee(drink)
            return 0
        else:
            return item


def make_coffee(drink):
    for item in menu[drink]["ingredients"]:
        resources[item] -= menu[drink]["ingredients"][item]


def coffee_machine():
    flag = True
    while flag:
        option = input("What would you like? (espresso/latte/cappuccino): ")
        if option == "report":
            report()
        elif option == "off":
            flag = False
        elif option in list(menu.keys()):
            resources_check = check_sufficient_resources(option)
            if resources_check == 0:
                if transaction(option):
                    print(f"Here is your {option}, enjoy!")
                else:
                    print("Sorry that's not enough money. Money refunded.")
            else:
                print(f"There is not enough {resources_check}")


coffee_machine()
